package com.aurora.data.data.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents the database table name for chat sessions.
 */
const val CHATS_TABLE_NAME = "chat_sessions"

/**
 * Represents a chat session entity in the database.
 * Each instance corresponds to a row in the [CHATS_TABLE_NAME] table.
 *
 * @property id The unique identifier for the chat session. Auto-generated by the database.
 * @property tripId Foreign key referencing the id of the Trip this chat session belongs to. Can be null if the session is not associated with a specific trip.
 * @property startTime The timestamp indicating when the chat session started, in milliseconds since epoch.
 */
@Entity(tableName = CHATS_TABLE_NAME)
data class ChatSessionEntity(
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "id") val id: Long = 0,
    /**
     * Foreign key referencing the id of the Trip this chat session belongs to.
     */
    @ColumnInfo(name = "trip_id") val tripId: Long?,
    @ColumnInfo(name = "start_time") val startTime: Long
)
